### PR TITLE
Ignore index.php files if they are just placeholders

### PR DESCRIPTION
**Pull request by jdarwood007**
This should let us add more index.php without needing to do a PR every time on this repo.  Also added it to check for __DIR__ usage in the future.

### CODE REVIEW

**Comment by live627** [comment]
one regex to rule them all
```php
// Stuff we will ignore.
$ignoreFiles = array(
	// Index files.
	'\./[A-Za-z0-9/]+/index\.php',
```

**Comment by jdarwood007** [comment]
I thought about that, but this also ensures we have the valid content in the file, matching our redirection handling.  If we don't care, we could do that.

**Comment by Sesquipedalian** [comment]
These index files can contain other variations of the same basic content. For example, the ones generated by SMF\Security::secureDirectory() are a bit different. I suggest something similar to @live627's idea:

```
// Stuff we will ignore.
$ignoreFiles = array(
	// Index files.
	'\./Sources/[\w/]+/index\.php',
```

**Review by Sesquipedalian — COMMENTED** [review]
These index files can contain other variations of the same basic content. For example, the ones generated by SMF\Security::secureDirectory() are a bit different. I suggest something similar to @live627's idea:

```
// Stuff we will ignore.
$ignoreFiles = array(
	// Index files.
	'\./Sources/[\w/]+/index\.php',
```

**Comment by jdarwood007** [comment]
Wouldn't it be better to ensure that our index.php placeholders align to what secureDirectory generates then?

**Comment by Sesquipedalian** [comment]
Yeah, I suppose so. And I would actually like secureDirectory() to change so that it matches what your regex looks for, rather than the other way around. The secureDirectory() ones look for Settings.php in the parent directory and then give up if it is not found. The ones your regex looks for check for an index.php file in the parent directory, which works better for namespaced code because it means that execution can pass up the directory tree until something actionable is found.

**Comment by jdarwood007** [comment]
Well that is what the current index.php logic does.

```
<?php

// Try to handle it with the upper level index.php. (it should know what to do.)
if (file_exists(dirname(dirname(__FILE__)) . '/index.php'))
	include (dirname(dirname(__FILE__)) . '/index.php');
else
	exit;

?>```

I can send a PR up to change all of the index.php to that, update secureDirectory to do that and then update this PR to look for that.  Except I will change the call of dirname(__FILE__) to __DIR__ for some micro optimization.

**Comment by Sesquipedalian** [comment]
Sounds like an excellent plan. 🙂

**Comment by jdarwood007** [comment]
@Sesquipedalian Sent up a separate file.  Once this is good, I can send up the pr for SMF.  Will include a updated github action to run that file.

**Review by Sesquipedalian — APPROVED** [review]

**Pull request merged**
